version: "3.8"
services:
  kdc:
    hostname: 'kdc.krb-test'
    container_name: 'krb-test-kdc'
    build:
      context: .
      dockerfile: ./kdc/Dockerfile
      #entrypoint: sh -c 'trap exit INT TERM; while :; do sleep 300; done'
    volumes:
      # speeds up testing, otherwise there probably won't be enough entropy for key generation
      - /dev/urandom:/dev/random
      #- ./krb5.conf:/etc/krb5.conf:r
      #- ./kdc/kadm5.acl:/var/lib/krb5kdc/kadm5.acl:r
      #- ./kdc/kdc.conf:/var/lib/krb5kdc/kdc.conf:r
      #- ./kdc/init.sh:/init.sh
      #- ./kdc-var-log/:/var/log/
      #- ./kdc-ash-history:/root/.ash_history
    #ports:
    #  - "749:749"
    #  - "88:88/udp"
  client:
    hostname: 'client.krb-test'
    container_name: 'krb-test-client'
    build:
      context: .
      dockerfile: ./client/Dockerfile
    entrypoint: sh -c 'trap exit INT TERM; while :; do sleep 300; done'
    depends_on:
      - kdc
    #volumes:
      #- ./krb5.conf:/etc/krb5.conf:r
      #- ./client-ash-history:/root/.ash_history
  sshd:
    hostname: 'sshd.krb-test'
    container_name: 'krb-test-sshd'
    build:
      context: .
      dockerfile: ./sshd/Dockerfile
    entrypoint: sh -c 'trap exit INT TERM; while :; do sleep 300; done'
    depends_on:
      - kdc
    #volumes:
      #- ./krb5.conf:/etc/krb5.conf:r
      #- ./sshd-ash-history:/root/.ash_history
    #ports:
    #  - "2222:22"
  ssh-client:
    hostname: 'ssh-client.krb-test'
    container_name: 'krb-test-ssh-client'
    build:
      context: .
      dockerfile: ./ssh-client/Dockerfile
    entrypoint: sh -c 'trap exit INT TERM; while :; do sleep 300; done'
    depends_on:
      - kdc
    #entrypoint: /bin/sh 
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    #volumes:
      #- ./krb5.conf:/etc/krb5.conf:r
      #- ./ssh-client-ash-history:/root/.ash_history
  ldap:
    hostname: 'ldap.krb-test'
    container_name: 'krb-test-ldap'
    build:
      context: .
      dockerfile: ./ldap/Dockerfile
    entrypoint: sh -c 'trap exit INT TERM; while :; do sleep 300; done'
    depends_on:
      - kdc
    volumes:
      #- ./krb5.conf:/etc/krb5.conf:r
      - ./ldap-ash-history:/root/.ash_history
    #ports:
    #  - "389:389"
    #  - "636:636"
networks:
  default:
    name: krb-test
